name: Buf

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [zyphor]
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Buf Format Check
        working-directory: ${{ matrix.module }}
        run: buf format --diff --exit-code

      - name: Buf Lint
        working-directory: ${{ matrix.module }}
        run: buf lint

      - name: Buf Breaking (on main)
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ matrix.module }}
        run: |
          buf breaking --against '.git#branch=main,ref=HEAD~1'

      - name: Buf Breaking (on PR)
        if: github.event_name == 'pull_request'
        working-directory: ${{ matrix.module }}
        run: |
          buf breaking --against '.git#branch=${{ github.base_ref }}'
